config/routes.rb
Rails.application.routes.draw do
  resources :subgrades
	resources :payment_policies
	resources :policies
	resources :hedges
	devise_for :users
	resources :grades
	resources :cars
	resources :takers
	root     "home#index"
	get 'policies/resumen', to: "policies/#resumen"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/hedge.rb
class Hedge < ApplicationRecord
	has_many :policy
end

app/controllers/hedges_controller.rb
class HedgesController < ApplicationController
  before_action :set_hedge, only: [:show, :edit, :update, :destroy]

  # GET /hedges
  # GET /hedges.json
  def index
    @hedges = Hedge.all
  end

  # GET /hedges/1
  # GET /hedges/1.json
  def show
  end

  # GET /hedges/new
  def new
    @hedge = Hedge.new
  end

  # GET /hedges/1/edit
  def edit
  end

  # POST /hedges
  # POST /hedges.json
  def create
    @hedge = Hedge.new(hedge_params)

    respond_to do |format|
      if @hedge.save
        format.html { redirect_to @hedge, notice: 'La Cobertura se creó exitosamente.' }
        format.json { render :show, status: :created, location: @hedge }
      else
        format.html { render :new }
        format.json { render json: @hedge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hedges/1
  # PATCH/PUT /hedges/1.json
  def update
    respond_to do |format|
      if @hedge.update(hedge_params)
        format.html { redirect_to @hedge, notice: 'La Cobertura se actualizó exitosamente.' }
        format.json { render :show, status: :ok, location: @hedge }
      else
        format.html { render :edit }
        format.json { render json: @hedge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hedges/1
  # DELETE /hedges/1.json
  def destroy
    @hedge.destroy
    respond_to do |format|
      format.html { redirect_to hedges_url, notice: 'La Cobertura se eliminó exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hedge
      @hedge = Hedge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hedge_params
      params.require(:hedge).permit(:name, :maximum_amount)
    end
end

app/helpers/hedges_helper.rb
module HedgesHelper
end

app/views/hedges/_form.html.erb
<%= form_for(hedge) do |f| %>
  <% if hedge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hedge.errors.count, "error") %> prohibited this hedge from being saved:</h2>

      <ul>
      <% hedge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name,class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :maximum_amount %>
    <%= f.text_field :maximum_amount,class:"form-control" %>
  </div>

 <div class="form-group  butons">
  <%= link_to 'Cancelar', policies_path, class: "hvr-skew-backward pull-right"   %>
  <%= f.submit "Aceptar", class: "hvr-skew-backward pull-right"  %>
</div>
<% end %>

app/views/hedges/edit.html.erb
<% if user_signed_in? && current_user.id==1 %>
<h1>Editar Cobertura</h1>

<%= render 'form', hedge: @hedge %>
<% end -%>

app/views/hedges/index.html.erb
<% if user_signed_in? && current_user.id==1 %>
<p id="notice"><%= notice %></p>

<h1>coberturas</h1>
<section class="table_flex_five pl-0 pr-0">
<table id="datatable" class="table table-hover">  <thead>
    <tr>
      <th>Nombre</th>
      <th>Monto Maximo</th>
      <th>Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @hedges.each do |hedge| %>
      <tr>
        <td><%= hedge.name %></td>
        <td><%= hedge.maximum_amount %></td>
        <td><%= link_to 'Show', hedge,class: "hvr-skew-backward" %>
        <%= link_to 'Edit', edit_hedge_path(hedge),class: "hvr-skew-backward" %>
        <%= link_to 'Destroy', hedge, method: :delete, data: { confirm: 'Are you sure?' },class: "hvr-skew-backward" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Cobertura', new_hedge_path,class: "hvr-skew-backward pull-left" %>
<% end -%>

app/views/hedges/new.html.erb
<% if user_signed_in? && current_user.id==1 %>
<h1>Nueva Cobertura</h1>

<%= render 'form', hedge: @hedge %>

<% end -%>

app/views/hedges/show.html.erb
<% if user_signed_in? && current_user.id==1 %>
<div class="jumbotron col-md-6 col-md-offset-3">
<h3>Datos de la cobertura</h3>
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @hedge.name %>
</p>

<p>
  <strong>Monto Maximo:</strong>
  <%= @hedge.maximum_amount %>
</p>

<%= link_to 'Editar', edit_hedge_path(@hedge) %> |
<%= link_to 'Regresar', hedges_path %>
</div>
<% end -%>