config/routes.rb
Rails.application.routes.draw do
  resources :subgrades
	resources :payment_policies
	resources :policies
	resources :hedges
	devise_for :users
	resources :grades
	resources :cars
	resources :takers
	root     "home#index"
	get 'policies/resumen', to: "policies/#resumen"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/payment_policy.rb
class PaymentPolicy < ApplicationRecord
	belongs_to :policy
end

app/controllers/payment_policies_controller.rb
class PaymentPoliciesController < ApplicationController
  before_action :set_payment_policy, only: [:show, :edit, :update, :destroy]

  # GET /payment_policies
  # GET /payment_policies.json
  def index
    @payment_policies = PaymentPolicy.all
  end

  # GET /payment_policies/1
  # GET /payment_policies/1.json
  def show
  end

  # GET /payment_policies/new
  def new
    @payment_policy = PaymentPolicy.new
    @policy= Policy.search_resumen_venta(params[:license_plate])

    unless params[:license_plate].nil?

      unless @policy.nil?
        respond_to do |format|
          format.js  { render 'payment_policies/buscar_placa.js.erb' }
        end
      else
        respond_to do |format|
          format.js  { render 'payment_policies/limpiar_buscar_placa.js.erb' }
        end
      end
    end
 

  end

  # GET /payment_policies/1/edit
  def edit
  end

  # POST /payment_policies
  # POST /payment_policies.json
  def create
    @payment_policy = PaymentPolicy.new(payment_policy_params)

    respond_to do |format|
      if @payment_policy.save
        format.html { redirect_to @payment_policy, notice: 'EL pago de Poliza se creó exitosamente.' }
        format.json { render :show, status: :created, location: @payment_policy }
      else
        format.html { render :new }
        format.json { render json: @payment_policy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payment_policies/1
  # PATCH/PUT /payment_policies/1.json
  def update
    respond_to do |format|
      if @payment_policy.update(payment_policy_params)
        format.html { redirect_to @payment_policy, notice: 'EL pago de Poliza se actualizó exitosamente.' }
        format.json { render :show, status: :ok, location: @payment_policy }
      else
        format.html { render :edit }
        format.json { render json: @payment_policy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_policies/1
  # DELETE /payment_policies/1.json
  def destroy
    @payment_policy.destroy
    respond_to do |format|
      format.html { redirect_to payment_policies_url, notice: 'EL pago de Poliza se eliminó exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_policy
      @payment_policy = PaymentPolicy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_policy_params
      params.require(:payment_policy).permit(:card_number, :name_card_holder, :expiration_date_card, :card_security_code, :number_quota,:policy_id)
    end
  end

app/helpers/payment_policies_helper.rb
module PaymentPoliciesHelper
end

app/views/payment_policies/_form.html.erb
<%= form_for(payment_policy) do |f| %>
  <% if payment_policy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment_policy.errors.count, "error") %> prohibited this payment_policy from being saved:</h2>

      <ul>
      <% payment_policy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="col-md-12">
 <%= f.text_field :policy_id ,hidden:"true",id:"policy_id" %>
</div>
  <div class="form-group">
    <%= f.label :numero_de_tarjeta %>
    <%= f.text_field :card_number, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :nombre_del_titular%>
    <%= f.text_field :name_card_holder, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :fecha_de_vencimiento %>
    <%= f.date_field :expiration_date_card , class:"form-control", onchange:"ValidarFecha(this)"%>
    <div id="msj"></div>
  </div>

  <div class="form-group">
    <%= f.label :codigo_de_seguridad %>
    <%= f.text_field :card_security_code, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :numero_de_coutas %>
    <%= f.number_field :number_quota, class:"form-control" %>
  </div>

<div class="form-group col-md-12 butons pr-0">
  <%= link_to 'Cancelar', policies_path, class: "hvr-skew-backward pull-right"   %>
  <%= f.submit "Aceptar", class: "hvr-skew-backward pull-right", id:"btn-payment-policies"  %>
</div>
<% end %>

app/views/payment_policies/buscar_placa.js.erb
$("#seccion-compra").show();

$("#seccion-compra").show();
$("#policy_id").val("<%= @policy.id %>");
$("#placa").text("<%= @policy.car.license_plate %>");
$("#age").text("<%= @policy.car.age %>");
$("#num_passengers").text("<%= @policy.car.num_passengers %>");
$("#cylinder").text("<%= @policy.car.cylinder %>");
$("#tons").text("<%= @policy.car.tons %>");
$("#grade").text("<%= @policy.car.subgrade.grade.name %>");
$("#mensaje").hide();

app/views/payment_policies/edit.html.erb
<% if user_signed_in? && current_user.id==1 %>
<h1>Editando Metodo Pago de Poliza</h1>

<%= render 'form', payment_policy: @payment_policy %>

<%= link_to 'Ver ', @payment_policy %> |
<%= link_to 'Regresar', payment_policies_path %>
<% end -%>

app/views/payment_policies/index.html.erb
<% if user_signed_in? && current_user.id==1 %>
<p id="notice"><%= notice %></p>

<h1>Pago de Polizas</h1>

<section class="table_flex_five pl-0 pr-0">
<table id="datatable" class="table table-hover">  
  <thead>
    <tr>
      <th>Numero de Tarjeta</th>
      <th>Nombre del titular</th>
      <th>Fecha de Expiracion de la tarjeta</th>
      <th>Codigo de seguridad de la tarjeta</th>
      <th>Numero de Coutas</th>
      <th>Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @payment_policies.each do |payment_policy| %>
      <tr>
        <td><%= payment_policy.card_number %></td>
        <td><%= payment_policy.name_card_holder %></td>
        <td><%= payment_policy.expiration_date_card %></td>
        <td><%= payment_policy.card_security_code %></td>
        <td><%= payment_policy.number_quota %></td>
        <td><%= link_to 'Ver', payment_policy,class: "hvr-skew-backward" %>
        <%= link_to 'Editar', edit_payment_policy_path(payment_policy),class: "hvr-skew-backward" %>
        <%= link_to 'Eliminar', payment_policy, method: :delete, data: { confirm: 'Are you sure?' },class: "hvr-skew-backward" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end -%>

<br>

app/views/payment_policies/new.html.erb
<% if user_signed_in? && current_user.id!=1 %>
<h1>New Payment Policy</h1>
<%= form_tag('/payment_policies/new', :method => "get", remote: true ) do %>
<div class="col-md-12 form-group pl-0 pr-0">
	<div class="col-md-6 pl-0 pr-0">
		<%= text_field_tag :license_plate, params[:license_plate], placeholder:"Ingrese placa", class:"form-control" %>
	</div>
	<div class="col-md-6 pull-left">
		<%= submit_tag "Buscar", data: {disable_with: "Buscando ..."}, :code => nil,class: "hvr-skew-backward pull-left btn-search" %>
	</div>
</div>
<%end%>

<div id="seccion-compra">
	<div class="jumbotron col-md-6"> 
		<h4 class="center"><strong>Datos del Vehiculo</strong></h4>
		<div class="col-md-12">	
			<div class="col-md-4"><p>placa</p></div><div class="col-md-8" ><p id="placa"></p></div>
		</div>
		<div class="col-md-12">	
			<div class="col-md-4"><p>año</p></div><div class="col-md-8" ><p id="age"></p></div>
		</div>
		<div class="col-md-12">	
			<div class="col-md-4"><p>numero de pasajeros</p></div><div class="col-md-8" ><p id="num_passengers"></p></div>
		</div>
		<div class="col-md-12">	
			<div class="col-md-4"><p>Cilindraje</p></div><div class="col-md-8" ><p id="cylinder"></p></div>
		</div>
		<div class="col-md-12">	
			<div class="col-md-4"><p>Toneladas</p></div><div class="col-md-8" ><p id="tons"></p></div>
		</div>
		<div class="col-md-12">	
			<div class="col-md-4"><p>Clase</p></div><div class="col-md-8" ><p id="grade"></p></div>
		</div>
	</div>
	<div class="col-md-6">
		<%= render 'form', payment_policy: @payment_policy %>
	</div>
</div>


<%= link_to 'Back', payment_policies_path %>
<% end -%>

app/views/payment_policies/show.html.erb
<% if user_signed_in? %>
<div class="jumbotron col-md-6 col-md-offset-3">
  <h3>Datos del Pago de Poliza</h3>
<p id="notice"><%= notice %></p>

<p>
  <strong>Numero de la tarjeta:</strong>
  <%= @payment_policy.card_number %>
</p>

<p>
  <strong>Nombre del titular:</strong>
  <%= @payment_policy.name_card_holder %>
</p>

<p>
  <strong>Fecha de expiración:</strong>
  <%= @payment_policy.expiration_date_card %>
</p>

<p>
  <strong>Codigo de seguridad:</strong>
  <%= @payment_policy.card_security_code %>
</p>

<p>
  <strong>Number quota:</strong>
  <%= @payment_policy.number_quota %>
</p>

<%= link_to 'Edit', edit_payment_policy_path(@payment_policy) %> |
<%= link_to 'Back', payment_policies_path %>
</div>
<% end -%>