config/routes.rb
Rails.application.routes.draw do
  resources :subgrades
	resources :payment_policies
	resources :policies
	resources :hedges
	devise_for :users
	resources :grades
	resources :cars
	resources :takers
	root     "home#index"
	get 'policies/resumen', to: "policies/#resumen"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/car.rb
class Car < ApplicationRecord
	belongs_to :subgrade
	has_many :policies

	def self.searchLicense_plate(license_plate)
		car = Car.where('"license_plate" = ?',"#{license_plate}").first 
		unless car.nil?
			return car
		else
			return nil
		end

	end

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'EL vehiculo se creó exitosamente..' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end
    def crear
    @car = Car.new(params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'EL vehiculo se creó exitosamente.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'EL vehiculo se actualizó exitosamente.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'EL vehiculo se eliminó exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:age, :num_passengers, :cylinder, :tons,:grade_id,:license_plate,:subgrade_id)
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_for(car) do |f| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="form-group">
    <%= f.label :Placa %>
    <%= f.text_field :license_plate,class:"form-control" %>
  </div>
  <div class="form-group input_100">
    <%= f.label :grade_id %>
  <%= f.collection_select :grade_id, Grade.all, :id, :name,class:"form-control",include_blank:"Seleccione" %>
  </div>
   <div class="form-group input_100">
    <%= f.label :subgrade_id %>
  <%= f.grouped_collection_select :subgrade_id, Grade.order(:name), :subgrades,:name,:id, :name, include_blank:"Seleccione" %>
  </div>
  

  <div class="form-group">
    <%= link_to 'Back', cars_path, class: "hvr-skew-backward pull-right" %>
    <%= f.submit  class: "hvr-skew-backward pull-right" %>
  </div>
<% end %>

app/views/cars/_form2.html.erb
<div id="myModal" class="modal fade" role="dialog">
  <div id="capa">

  </div>
  <div class="modal-dialog" >
    <!-- Modal content-->

    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" id="button-equis">&times;</button>
        <h1 class="title-center">Registrar Beneficiario</h1>
      </div>ss
      <div class="modal-body">
       <%= form_for(car) do |f| %>
       <% if car.errors.any? %>
       <div id="error_explanation">
        <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

        <ul>
          <% car.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
      <div class="form-group">
        <%= f.label :Placa %>
        <%= f.text_field :license_plate,class:"form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :clase %>
        <%= f.collection_select :grade_id, Grade.all, :id, :name,class:"form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :age %>
        <%= f.number_field :age,class:"form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :num_passengers %>
        <%= f.number_field :num_passengers,class:"form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :cylinder %>
        <%= f.number_field :cylinder,class:"form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :tons %>
        <%= f.number_field :tons,class:"form-control" %>
      </div>

      <div class="form-group">
        <%= link_to 'Back', cars_path, class: "btn btn-danger" %>
        <%= f.submit  class: "btn btn-success" %>
      </div>
      <% end %>
    </div>
    <div class="modal-footer">

    </div>
  </div>

</div>
</div>

app/views/cars/edit.html.erb
<% if user_signed_in? && current_user.id==1 %>
<h1>Editar Vehiculo</h1>

<%= render 'form', car: @car %>

<% end -%>

app/views/cars/index.html.erb
<% if user_signed_in? && current_user.id==1 %>
<p id="notice"><%= notice %></p>

<h1>Vehiculos</h1>
<section class="table_flex_five">
<table id="datatable">
  <thead>
    <tr>
      <th>Placa</th>
      <th>Clase</th>
      <th>Subclase</th>
      <th>Edad</th>
      <th>Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
    <tr>
       <td><%= car.license_plate %></td>
      <td><%= car.subgrade.grade.name %></td>
      <td><%= car.subgrade.name %></td>
      <td><%= car.age %></td>
      <td><%= link_to 'Ver', car,class: "hvr-skew-backward"  %>
      <%= link_to 'Edita', edit_car_path(car),class: "hvr-skew-backward"  %>
      <%= link_to 'Eliminar', car, method: :delete, data: { confirm: 'Are you sure?' } ,class: "hvr-skew-backward" %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</section>
<br>

<%= link_to 'nuevo', new_car_path,class: "hvr-skew-backward pull-left" %>

<% end -%>

app/views/cars/new.html.erb
<% if user_signed_in? && current_user.id==1 %>
<h1>Nuevo Vehiculo</h1>

<%= render 'form', car: @car %>

<%end%>

app/views/cars/new.js.erb
$(".a-unique-class").html('<%= j render "cars/_form" %>')

app/views/cars/show.html.erb
<% if user_signed_in? && current_user.id==1 %>
<div class="jumbotron col-md-6 col-md-offset-3">
	<h3>Datos del Vehiculo</h3>
	<p id="notice"><%= notice %></p>
	<p>
		<strong>Age:</strong>
		<%= @car.age %>
	</p>

	<p>
		<strong>Num passengers:</strong>
		<%= @car.num_passengers %>
	</p>

	<p>
		<strong>Cylinder:</strong>
		<%= @car.cylinder %>
	</p>

	<p>
		<strong>Tons:</strong>
		<%= @car.tons %>
	</p>
		<%= link_to 'Editar', edit_car_path(@car) %> 
		<%= link_to 'Regresar', cars_path %>
</div>
<% end -%>