config/routes.rb
Rails.application.routes.draw do
  resources :subgrades
	resources :payment_policies
	resources :policies
	resources :hedges
	devise_for :users
	resources :grades
	resources :cars
	resources :takers
	root     "home#index"
	get 'policies/resumen', to: "policies/#resumen"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/policy.rb
class Policy < ApplicationRecord
	belongs_to :hedge
	belongs_to :user
	belongs_to :car
	has_one :payment_policy

	def self.search_resumen_venta(license_plate)
		resumen = Policy.joins(:car).where('"cars"."license_plate"=?',"#{license_plate}").last 
		unless resumen.nil?
			return resumen
		else
			return nil
		end
	end
end

app/controllers/policies_controller.rb
class PoliciesController < ApplicationController
  before_action :set_policy, only: [:show, :edit, :update, :destroy]

  # GET /policies
  # GET /policies.json
  def index
    @policies = Policy.all
  end

  # GET /policies/1
  # GET /policies/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf do
         render template:'policies/resumen', pdf: 'Resumen de Compra', orientation:'Landscape' 
      end
    end
  end

def resumen
render pdf: "resumen"  
end

  # GET /policies/new
  def new
      @policy = Policy.new
    @car= Car.searchLicense_plate(params[:license_plate])
    @policy_existe= Policy.search_resumen_venta(params[:license_plate])
    unless  @policy_existe.nil?
          respond_to do |format|
            format.js  { render 'policies/policy_existe.js.erb' }
          end
    else
    
      unless params[:license_plate].nil?
        puts "no existe"
        unless @car.nil?
          respond_to do |format|
            format.js  { render 'policies/buscar_placa.js.erb' }
          end
        else
          respond_to do |format|
            format.js  { render 'policies/limpiar_buscar_placa.js.erb' }
          end
        end
      end
    end
  end

  # GET /policies/1/edit
  def edit
  end

  # POST /policies
  # POST /policies.json
  def create
    @policy = Policy.new(policy_params)
    @policy.user_id = current_user.id
    respond_to do |format|
      if @policy.save
        PolicyMailer.compra_poliza(@policy).deliver_now
        format.html { redirect_to @policy, notice: 'La Compra de Poliza se creó exitosamente.' }
        format.json { render :show, status: :created, location: @policy }
      else
        format.html { render :new }
        format.json { render json: @policy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /policies/1
  # PATCH/PUT /policies/1.json
  def update
    respond_to do |format|
      if @policy.update(policy_params)
        format.html { redirect_to @policy, notice: 'La Compra de Poliza se actualzó exitosamente.' }
        format.json { render :show, status: :ok, location: @policy }
      else
        format.html { render :edit }
        format.json { render json: @policy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /policies/1
  # DELETE /policies/1.json
  def destroy
    @policy.destroy
    respond_to do |format|
      format.html { redirect_to policies_url, notice: 'La Compra de Poliza se eliminó exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_policy
      @policy = Policy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def policy_params
      params.require(:policy).permit(:total_amount, :valid_since,:hedge_id, :car_id)
    end
  end

app/helpers/policies_helper.rb
module PoliciesHelper
end

app/views/policies/_form.html.erb
<%= form_for(policy) do |f| %>
<% if policy.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(policy.errors.count, "error") %> prohibited this policy from being saved:</h2>

  <ul>
    <% policy.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="col-md-12">
 <%= f.text_field :car_id ,hidden:"true",id:"car_id" %>
</div>

<div class="form-group col-md-12 input_100">
  <%= f.label :cobertura %>
  <%= f.collection_select :hedge_id, Hedge.all, :id, :name, class:"form-control",include_blank:"Seleccione" %>
</div>

<div class="form-group col-md-12">
  <%= f.label :total_amount %>
  <%= f.text_field :total_amount ,hidden:"true",class:"form-control" %>
  <p id="total_amount"></p>
</div>

<div class="form-group col-md-12">
  <%= f.label :valid_since %>
  <%= f.date_field :valid_since, class:"form-control"  %>
</div>

<div class="form-group col-md-12 butons">
  <%= link_to 'Cancelar', policies_path, class: "hvr-skew-backward pull-right"   %>
  <%= f.submit "Aceptar", class: "hvr-skew-backward pull-right"  %>
</div>
<% end %>

app/views/policies/buscar_placa.js.erb
$("#seccion-compra").show();
$("#car_id").val("<%= @car.id %>");
$("#placa").text("<%= @car.license_plate %>");
$("#age").text("<%= @car.age %>");
$("#num_passengers").text("<%= @car.num_passengers %>");
$("#cylinder").text("<%= @car.cylinder %>");
$("#tons").text("<%= @car.tons %>");
$("#grade").text("<%= @car.subgrade.grade.name %>");
$("#mensaje").hide();

var total_amount= <%= @car.subgrade.bonus +  0.50*@car.subgrade.bonus + 1610 %>;
$("#policy_total_amount").val(total_amount);
$("#policy_total_amount").hide();
$("#total_amount").text(total_amount);

app/views/policies/car.js.erb
$("#modal-window").html("<%= escape_javascript(render 'cars/form2') %>")

app/views/policies/edit.html.erb
<% if user_signed_in? && current_user.id==1 %>
<h1>Editing Policy</h1>

<%= render 'form', policy: @policy %>

<%= link_to 'Show', @policy %> |
<%= link_to 'Back', policies_path %>
<% end -%>

app/views/policies/index.html.erb
<% if user_signed_in? && current_user.id==1 %>
<p id="notice"><%= notice %></p>

<h1>Polizas</h1>
<section class="table_flex_five pl-0 pr-0">
<table id="datatable" class="table table-hover">
  <thead>
    <tr>
      <th>Placa</th>
      <th>Monto Total</th>
      <th>Valido hasta</th>
      <th>Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @policies.each do |policy| %>
      <tr>
        <td><%= policy.car.license_plate %></td>
        <td><%= policy.total_amount %></td>
        <td><%= policy.valid_since %></td>
        <td><%= link_to 'Ver', policy ,class: "hvr-skew-backward" %>
        <%= link_to 'Editar', edit_policy_path(policy),class: "hvr-skew-backward" %>
        <%= link_to 'Eliminar', policy, method: :delete, data: { confirm: 'Are you sure?' },class: "hvr-skew-backward" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Poliza', new_policy_path,class: "hvr-skew-backward pull-left" %>
<% end -%>

app/views/policies/limpiar_buscar_placa.js.erb
$("#mensaje").show();
$("#mensaje").text("No existe la placa");

$("#seccion-compra").hide();
$("#car_id").val("");
$("#placa").text("");
$("#age").text("");
$("#num_passengers").text("");
$("#cylinder").text("");
$("#tons").text("");
$("#grade").text("");

app/views/policies/new.html.erb
<% if user_signed_in? &&  current_user.id!=1 %>
<h1>Nueva Poliza</h1>

<% unless current_user.taker.nil?%>
<%= form_tag('/policies/new', :method => "get", remote: true ) do %>
<div class="col-md-12 form-group pl-0 pr-0">
	<div class="col-md-6 pl-0 pr-0">
		<%= text_field_tag :license_plate, params[:license_plate], placeholder:"Ingrese placa", class:"form-control" %>
	</div>
	<div class="col-md-6 pull-left">
		<%= submit_tag "Buscar", data: {disable_with: "Buscando ..."}, :code => nil,class: "hvr-skew-backward pull-left btn-search" %>
	</div>
</div>
<%end%>
<% unless @existe.nil? %>
	<%= @existe  %>
<%end%>

<div class="col-md-12 pl-0 pr-0">
<div class="alert alert-danger" id="mensaje">
</div>
</div>
<div ></div>
<div id="seccion-compra">
	<div class="jumbotron col-md-6"> 
		<h4 class="center"><strong>Datos del Vehiculo</strong></h4>
		<div class="col-md-12">	
			<div class="col-md-4"><p>placa</p></div><div class="col-md-8" ><p id="placa"></p></div>
		</div>
		<div class="col-md-12">	
			<div class="col-md-4"><p>año</p></div><div class="col-md-8" ><p id="age"></p></div>
		</div>
		<div class="col-md-12">	
			<div class="col-md-4"><p>numero de pasajeros</p></div><div class="col-md-8" ><p id="num_passengers"></p></div>
		</div>
		<div class="col-md-12">	
			<div class="col-md-4"><p>Cilindraje</p></div><div class="col-md-8" ><p id="cylinder"></p></div>
		</div>
		<div class="col-md-12">	
			<div class="col-md-4"><p>Toneladas</p></div><div class="col-md-8" ><p id="tons"></p></div>
		</div>
		<div class="col-md-12">	
			<div class="col-md-4"><p>Clase</p></div><div class="col-md-8" ><p id="grade"></p></div>
		</div>
	</div>
	<div class="col-md-6">
		<%= render 'form', policy: @policy %>
	</div>
</div>
<%else%>
<div class="alert alert-danger">
	<p>Para Comprar debe estar cargado tu perfil,</p><%= link_to 'Cargar perfil', new_taker_path %></p>
</div>
<%end%>
<% end -%>

app/views/policies/policy_existe.js.erb
$("#mensaje").show();
$("#mensaje").text("Este vehiculo ya se encuentra asociado a una poliza.");

app/views/policies/resumen.pdf.erb
<!doctype html>
<html>
<head>
  <meta charset='utf-8' />
  <%= wicked_pdf_stylesheet_link_tag "pdf" -%>
  <%= wicked_pdf_javascript_include_tag "number_pages" %>
</head>
<body onload='number_pages'>
  <div class="col-12">
  </div>
  <div class="col-4"></div>
  <div class="col-6 pl-0">
  	<div class="col-12 cab-thead text-center">
  		<p>Datos de la Compra</p>
  	</div>
  	<div class="col-6 ">
  		<strong>Total a Pagar</strong>
  	</div>
  	<div class="col-6">
  		<strong> <%= @policy.total_amount %></strong>
  	</div>
  	<div class="col-6 ">
  		<strong>Cobertura</strong>
  	</div>
  	<div class="col-6">
  		<p><strong> <%= @policy.hedge.name %></strong></p>
  	</div>
  	<div class="col-6 ">
  		<strong>Cobertura</strong>
  	</div>
  	<div class="col-6">
  		<strong> <%= @policy.valid_since %></p></strong>
  	</div>
  </div>


 </div>
</body>
</html>

app/views/policies/show.html.erb
<% if user_signed_in?  %>
<div class="jumbotron col-md-6 col-md-offset-3">
	<h3>Datos de la Compra</h3>
<p id="notice"><%= notice %></p>

<p>
  <strong>Total a Pagars:</strong>
  <%= @policy.total_amount %>
</p>
<p><strong>Cobertura</strong>
 <%= @policy.hedge.name %></p>
<p>

  <strong>Valid since:</strong>
  <%= @policy.valid_since %>
</p>


<%= link_to 'Edit', edit_policy_path(@policy),class:"fa fa-download" %> 
<%= link_to 'Back', policies_path,class:"fa fa-download" %>
<%= link_to "Exportar a PDF", policy_path(format: "pdf") , :target => "_blank", class:"fa fa-download" %>  
</div>
<% end -%>